#!/system/bin/sh
# W03Tweaks

#Disable fair sleepers
echo "NO_GENTLE_FAIR_SLEEPERS" > /sys/kernel/debug/sched_features

#Enable multi-core load balance
echo "0" > /sys/devices/system/cpu/sched_mc_power_saving

#Enable AFTR+LPA sleep
echo "3" > /sys/module/cpuidle_exynos4/parameters/enable_mask

#PegasusQ Tweaks
echo "500000" > /sys/devices/system/cpu/cpufreq/pegasusq/freq_for_responsiveness

echo "40000" > /sys/devices/system/cpu/cpufreq/pegasusq/sampling_rate

echo "80" > /sys/devices/system/cpu/cpufreq/pegasusq/up_threshold

echo "50" > /sys/devices/system/cpu/cpufreq/pegasusq/up_threshold_at_min_freq

echo "500000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_1_1
echo "300000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_2_0
echo "600000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_2_1
echo "400000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_3_0
echo "700000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_3_1
echo "500000" > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_4_0

#Read Ahead KB
echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb
echo "2048" > /sys/devices/virtual/bdi/179:16/read_ahead_kb
echo "2048" > /sys/devices/virtual/bdi/179:32/read_ahead_kb
echo "2048" > /sys/devices/virtual/bdi/179:48/read_ahead_kb

#ROW default scheduler
echo "row" > /sys/block/mmcblk0/queue/scheduler
sleep 60s
echo "row" > /sys/block/mmcblk0/queue/scheduler
sleep 60s
echo "row" > /sys/block/mmcblk0/queue/scheduler
sleep 180s
echo "row" > /sys/block/mmcblk0/queue/scheduler
