#!/system/bin/sh
#
# Copy camera firmware to /data/cfw
#

function copy_fw()
{
	busybox cp /system/vendor/firmware/SlimISP_*.bin /data/cfw/

	busybox chown system /data/cfw/*
	busybox chgrp media /data/cfw/*
	busybox chmod 0775 /data/cfw/*
}

# background that stuff
copy_fw &
