#!/system/bin/sh
# Optimize SQlite databases of apps
# Taken from thunderbolt! by pikachu01 @ XDA
# Smart Optimizing by ImbaWind @ XDA
# Adrenaline Engine Specified

. /system/etc/init.d.config

if $sqlite_hack
then
	echo "Now Optimizing sqlite databases"
	for i in \
	`busybox find /data -iname "*.db"`; 
	do \
		/system/xbin/sqlite3 $i 'VACUUM;'; 
		/system/xbin/sqlite3 $i 'REINDEX;'; 
	done;

	if [ -d "/dbdata" ]; then
		for i in \
		`busybox find /dbdata -iname "*.db"`; 
		do \
			/system/xbin/sqlite3 $i 'VACUUM;'; 
			/system/xbin/sqlite3 $i 'REINDEX;'; 
		done;
	fi;


	if [ -d "/datadata" ]; then
		for i in \
		`busybox find /datadata -iname "*.db"`; 
		do \
			/system/xbin/sqlite3 $i 'VACUUM;'; 
			/system/xbin/sqlite3 $i 'REINDEX;'; 
		done;
	fi;


	for i in \
	`busybox find /sdcard -iname "*.db"`; 
	do \
		/system/xbin/sqlite3 $i 'VACUUM;'; 
		/system/xbin/sqlite3 $i 'REINDEX;'; 
	done;
fi
