#!/system/bin/sh

BSND=/system/media/audio/ui/bootup.wav

if [ -r /data/local/audio/bootup.wav ]; then

  BSND=/data/local/audio/bootup.wav

fi

if [ -r $BSND ]; then
  /data/local/bin/tinyplay $BSND &
fi