#!/system/bin/sh

while true
do
	echo "Gsiff Monitor: checking usage .. "
	pct=`top -n 1 | grep gsiff_daemon | awk '{ printf "%d", $3 }'`
	
	if [ "$pct" -gt "10" ]
	then
		gspid=`top -n 1 | grep gsiff_daemon | awk '{ printf "%d", $1 }'`
		echo "Gsiff Monitor: gsiff_daemon (pid $gspid) using more than 10% CPU - killing it."		
		kill $gspid
	else
		echo "Gsiff Monitor: usage at $pct %"
	fi
	
	sleep 60
done &

echo "Started gsiff daemon monitor process."
